[main]
modules=/path/to/tui-lock.so

# all setting with their default values
[tui-lock]

# enable logging
debug=false

font-family=Monospace
font-size=12
login-text=Login

# --- BORDER SETTINGS ---
# border style 1 = single line border, 2 = double line, 3 = single line rounded
border-style=1
# width of prompt box (in pixels)
border-x=320
# height of prompt box (in pixels)
border-y=180

# --- COMMANDS ---
# $USER gets resolved to current username
logout-cmd=loginctl terminate-user $USER
shutdown-cmd=systemctl -i poweroff
reboot-cmd=systemctl reboot

# --- THEMEING ---
# terminal green theme
# color of "Login" text
login-color=#FFFFFF
# color of "Username" and "Password" text
prompt-color=##33FF00
# color of border
border-color=#33FF00
# background color
bg-color=#000000
# color of foreground elements 
# examples: logout/poweroff/reboot text at bottom, username, password asteriks
fg-color=#FFFFFF
