[main]
modules=/path/to/tui-lock.so

[tui-lock]
font-family=Terminus
font-size=14
login-text=Hello $USER
border-style=1
# shutdown hyprland properly on logout
logout-cmd=hyprshutdown
# gruvbox color theme
border-color=#ebdbb2
bg-color=#282828
fg-color=#ebdbb2
login-color=#8ec07c
prompt-color=#b8bb26

